# Generated by configure-macos.sh on Sat Aug 22 03:47:49 UTC 2026
SRCDIR                   := /Users/nileshchakraborty/workspace/proton
BUILD_NAME               := proton-macos-release
INTERNAL_TOOL_NAME       := proton-macos-release-proton
TARGET_OS                := macos
TARGET_ARCH              := arm64
CONTAINER_ENGINE         := none
ROOTLESS_CONTAINER       := 0
MACOS_SDK_PATH           := /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
MACOS_DEPLOYMENT_TARGET  := 11.0
ENABLE_CCACHE            := 0

include $(SRCDIR)/Makefile.in
